version: "3.3"

services:

  api:
    build:
      context: .
    image: test-node
    env_file: docker-compose.env
    depends_on:
      - postgres
    ports:
      - 3000:3000
    networks:
      - internal
    restart: always

  postgres:
    image: postgres:14-alpine
    env_file: docker-compose.env
    ports: 
      - 5432:5432
    networks:
      - internal

networks:
  internal: